basePath: /
definitions:
  model.ServiceUpdateUserSubscription:
    properties:
      id:
        example: 7639ca88-80df-4d91-ae20-78ac3431ee11
        type: string
      price:
        example: 400
        type: integer
      service_name:
        example: Yandex Plus
        type: string
      start_date:
        example: 07-2025
        type: string
      user_id:
        example: 7639ca88-80df-4d91-ae20-78ac3431ee11
        type: string
    type: object
  model.ServiceUserSubscription:
    properties:
      price:
        example: 400
        type: integer
      service_name:
        example: Yandex Plus
        type: string
      start_date:
        example: 07-2025
        type: string
      user_id:
        example: 7639ca88-80df-4d91-ae20-78ac3431ee11
        type: string
    type: object
  model.UserSubscription:
    properties:
      id:
        example: 7639ca88-80df-4d91-ae20-78ac3431ee11
        type: string
      price:
        example: 400
        type: integer
      service_name:
        example: Yandex Plus
        type: string
      start_date:
        example: 07-2025
        type: string
      user_id:
        example: 7639ca88-80df-4d91-ae20-78ac3431ee11
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: REST API for managing subscriptions
  title: Subscription service API
  version: "1.0"
paths:
  /subscription/:
    patch:
      consumes:
      - application/json
      description: Partial update of subscription
      parameters:
      - description: Update data
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/model.ServiceUpdateUserSubscription'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Update subscription
      tags:
      - subscription
    post:
      consumes:
      - application/json
      description: create new subscription for user
      parameters:
      - description: Subscription data
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/model.ServiceUserSubscription'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: create subscription
      tags:
      - subscription
  /subscription/{id}/:
    delete:
      parameters:
      - description: Subscription ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Delete subscription
      tags:
      - subscription
    get:
      parameters:
      - description: Subscription ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.UserSubscription'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      tags:
      - subscription
  /subscription/sum/:
    get:
      description: Calculate total price for subscriptions in specified period by
        user or service name
      parameters:
      - description: User ID
        in: query
        name: user_id
        type: string
      - description: Service name
        in: query
        name: service_name
        type: string
      - description: Start date (MM-YYYY)
        in: query
        name: start_date
        required: true
        type: string
      - description: End date (MM-YYYY)
        in: query
        name: end_date
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: integer
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get total subscription cost
      tags:
      - subscription
  /subscriptions/:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.UserSubscription'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get all subscriptions
      tags:
      - subscription
  /subscriptions/{user_id}/:
    get:
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.UserSubscription'
            type: array
      summary: Get subscriptions by user
      tags:
      - subscription
swagger: "2.0"
